development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:f708a2fdfe8ef8c94a58649d6e6a1d28@pearlfish.redistogo.com:9530/
  channel_prefix: message-me_production
